// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-weak-words.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_weak_words_default = defineTool2({
  name: "list_weak_words",
  title: "List weak Black Book words",
  description: "Return the signed-in user's most-missed Black Book vocabulary items (words they got wrong most often in practice), grouped by category.",
  inputSchema: {
    category: z2.enum(["synonyms_antonyms", "idioms_phrases", "one_word_substitutions"]).optional().describe("Optional category filter."),
    limit: z2.number().int().min(1).max(100).default(20).describe("Max items to return.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bb_practice_attempts").select("item_id, category, question").eq("user_id", ctx.getUserId()).eq("is_correct", false);
    if (category) query = query.eq("category", category);
    const { data, error } = await query.limit(2e3);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const key = row.item_id;
      const prev = counts.get(key);
      if (prev) prev.wrong++;
      else counts.set(key, { item_id: row.item_id, category: row.category, question: row.question, wrong: 1 });
    }
    const ranked = Array.from(counts.values()).sort((a, b) => b.wrong - a.wrong).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(ranked, null, 2) }],
      structuredContent: { items: ranked }
    };
  }
});

// src/lib/mcp/tools/list-bb-sessions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bb_sessions_default = defineTool3({
  name: "list_bb_sessions",
  title: "List recent Black Book practice sessions",
  description: "Return the signed-in user's recent Black Book practice sessions with score and category.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("Max sessions to return.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("bb_practice_sessions").select("id, category, total, correct, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "agtibwrtzxiwtozikoij";
var mcp_default = defineMcp({
  name: "clipcraft-learn-mcp",
  title: "ClipCraft Learn",
  version: "0.1.0",
  instructions: "Tools for the ClipCraft Learn study app. Use `list_weak_words` to see the user's most-missed Black Book vocab, `list_bb_sessions` for recent practice sessions, and `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_weak_words_default, list_bb_sessions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
