ALTER TABLE public.ssc_black_book_items ADD COLUMN IF NOT EXISTS hint text;

WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at ASC, id ASC) AS rn
  FROM public.ssc_black_book_items
  WHERE category = 'idiom'
),
hints(rn, hint) AS (
  VALUES
  (1, 'Jhadi ke aas-paas ghoom raha hai. Seedha mudde par nahi aa raha.'),
  (2, 'Hathoda seedha keel ke beech me laga.'),
  (3, 'Beans gir gaye. Sab bahar aa gaya. Secret bhi.'),
  (4, 'Dard sehne ke liye goli daant se daba li.'),
  (5, 'Kaale baadal sir ke upar. Body bilkul fresh nahi lag rahi.'),
  (6, 'Cheez kharidi aur laga haath-pair hi chale gaye.'),
  (7, 'Neela chaand dikh gaya. Bahut hi rare.'),
  (8, 'Cake ka chhota piece. Aaram se kha liya.'),
  (9, 'Laptop band. Aaj ka kaam khatam.'),
  (10, 'Seedha bistar par gira aur so gaya.'),
  (11, 'Bag khola aur billi bahar nikal gayi. Secret bhi.'),
  (12, 'Baraf tod di. Ab baat shuru.'),
  (13, 'Pathar samajh kar uthaya. Andar heera nikla.'),
  (14, 'Saaf aasman se achanak bijli gir gayi.'),
  (15, 'Kulhadi zameen me daba di. Jhagda khatam.'),
  (16, 'Raat bhar diya jal raha hai. Padhai chal rahi hai.'),
  (17, 'Hans ke peeche bhaag rahe ho. Kabhi pakad nahi paoge.'),
  (18, 'Stage par khade ho. Galti ki saza sunni padegi.'),
  (19, 'Badalon ke upar khushi se uchhal raha hai.'),
  (20, 'Baad par baitha hai. Kisi side nahi utar raha.'),
  (21, 'Muh me itna bhar liya ki chaba nahi pa raha.'),
  (22, 'Machhli paani se bahar tadap rahi hai.'),
  (23, 'Khud hi apna trumpet baja raha hai.'),
  (24, 'Topi girte hi turant daud pada.'),
  (25, 'Doodh gir gaya. Ab ro kar fayda nahi.'),
  (26, 'Mare hue ghode ko baar-baar peet raha hai.'),
  (27, 'Muh khola aur sab uski baat sunte hi reh gaye.'),
  (28, 'Khane me namak ki chhutki daal kar hi taste kiya.'),
  (29, 'Match se pehle sab bol rahe hain, "Ja, jeet ke aa!"'),
  (30, 'Shortcut lene ke chakkar me kaam aadha-adhura kar diya.'),
  (31, 'Ghadi ki last minute chal rahi hai. Tab kaam shuru hua.'),
  (32, 'Kandhe par kulhadi lekar badla lene nikla hai.'),
  (33, 'Kamre me kuch gadbad hai. Chuhe ki smell aa rahi hai.'),
  (34, 'Police gusse me khadi hai. Tu mushkil me phans gaya.'),
  (35, 'Chitthi ke shabdon ke beech chhupa message dhoondh raha hai.'),
  (36, 'Dono ek doosre ki aankhon me dekhkar haan bol rahe hain.'),
  (37, 'Baarish ho ya dhoop, saath-saath chal rahe hain.'),
  (38, 'Boxer ne gloves utaar diye. Match chhod diya.'),
  (39, 'Har patthar palat diya. Kuch bhi nahi chhoda.'),
  (40, 'Saste sikke zameen par har jagah pade hain.'),
  (41, 'Jalti aag me petrol daal diya.'),
  (42, 'Design fail hua. Sab mita kar phir se drawing bana rahe hain.'),
  (43, 'Chai ke cup me chhota sa tufaan mach gaya.'),
  (44, 'Bahut sakht akhrot. Toot hi nahi raha.'),
  (45, 'Samundar ke beech khada hai. Samajh nahi aa raha kidhar jaaye.'),
  (46, 'Bus nikal gayi. Tu bas dekhte reh gaya.'),
  (47, 'Saand ke seedha seeng pakad liye.'),
  (48, 'Kaan band kar liye. Kuch sunna hi nahi.'),
  (49, 'Kutta galat ped ke niche bhonk raha hai.'),
  (50, 'Kisi ko dekhte hi muh pher liya. Bilkul thanda behaviour.'),
  (51, 'Daudne ko taiyar ghoda. Bas lagaam pakad kar rok liya.'),
  (52, 'Ek hi naav me sab saath baithe hain.'),
  (53, 'Race shuru hone se pehle hi daud pada.'),
  (54, 'Aasmaan se billi aur kutte baras rahe hain.'),
  (55, 'Kaala ghoda chupchaap race jeet gaya.'),
  (56, 'Patli baraf par sambhal-sambhal kar chal raha hai.'),
  (57, 'Calendar ki date laal rang se chamak rahi hai.'),
  (58, 'Ghaas me saanp chhup kar baitha hai.'),
  (59, 'Saari saavdhani hawa me uda di.'),
  (60, 'Violin ki tarah perfectly tuned aur fit.'),
  (61, 'Pul jala diya. Ab wapas nahi ja sakte.'),
  (62, 'Ek hi chhalang me bahut aage nikal gaya.'),
  (63, 'Finish line ke baad bhi chalta hi raha.'),
  (64, 'Dhuaan utha aur sab kuch gayab ho gaya.'),
  (65, 'Shaitaan ki side lekar jaan-boojhkar behas kar raha hai.'),
  (66, 'Safed haathi. Bahut mehenga, kaam ka nahi.'),
  (67, 'Safed bhedon ke beech ek kaali bhed.'),
  (68, 'Sabke saamne jhuk kar pie kha raha hai.'),
  (69, 'Bade nariyal ko chhote nutshell me band kar diya.'),
  (70, 'Bheed dekhi aur bina soche usi gaadi me chadh gaya.'),
  (71, 'Beech raste me akela chhod kar sab chale gaye.'),
  (72, 'Dost ki taang kheench kar hans raha hai.'),
  (73, 'Ball ab tumhare court me aa gayi.'),
  (74, 'Sher ne sabse bada hissa le liya.'),
  (75, 'Purana panna palat kar naya panna khol diya.'),
  (76, 'Murga aur saand ki bilkul bakwaas kahani suna raha hai.'),
  (77, 'Dono kaan khol kar dhyan se sun raha hai.'),
  (78, 'Kabhi chala, kabhi ruk gaya.'),
  (79, 'Daant ki sirf bahar wali skin se bach gaya.'),
  (80, 'Daant aur naakhun se poori taqat laga kar lad raha hai.'),
  (81, 'Kali ko phool banne se pehle hi tod diya.'),
  (82, 'Aankh khuli hai, phir bhi jaan-boojhkar andekha kar diya.'),
  (83, 'Purane lakdi ke tukde jaisa bilkul waise hi naya tukda.'),
  (84, 'Topi par ek aur sundar pankh lag gaya.'),
  (85, 'Sir pakad kar baitha hai. Koi idea nahi bacha.'),
  (86, 'Dono haathon me laddoo mil gaye.'),
  (87, 'Stage par jaane se pehle pair thande pad gaye.'),
  (88, 'Chhoti cheez haath se nikal kar bahut badi ho gayi.'),
  (89, 'Haath me chupke se paise rakh diye.'),
  (90, 'Kamar ke neeche vaar kar diya.'),
  (91, 'Puri kitab Greek me likhi hai. Kuch samajh nahi aa raha.'),
  (92, 'Balti ko laat maari. (Yaad karo, scene se guess nahi hoga.)'),
  (93, 'Oont ki peeth par aakhri tinka rakh diya.'),
  (94, 'Khud ko sambhala aur phir se khada ho gaya.'),
  (95, 'Sir ke upar kaale baadal mandra rahe hain.'),
  (96, 'Hathiyaar utha kar gusse me khade ho gaye.'),
  (97, 'Dhoop me dost. Baarish aate hi gayab.'),
  (98, 'Bas do kadam ki doori par hai.'),
  (99, 'Haath par laal rang laga hua tha. Chori karte pakda gaya.'),
  (100, 'Room me 40 ft ka haathi. Sab dekh rahe hain. Bas ignore kar rahe hain.'),
  (101, 'Dono haath gloves ki tarah perfectly fit. Hamesha saath-saath.'),
  (102, 'Haath badhaya, par door hi rok liya.'),
  (103, 'Garam cake aaye aur turant saare bik gaye.'),
  (104, 'Sirf gulaabon ka naram bistar. Koi takleef nahi.'),
  (105, 'Aankhon me sabse pyara seb sambhal kar rakha hai.'),
  (106, 'Do log ek doosre ko dekhte hi muh bana rahe hain.'),
  (107, 'Band darwaza bhi kisi tarah khol hi diya.'),
  (108, 'Belche ko belcha hi bola. Sach seedha muh par.'),
  (109, 'Gol-gol ghoom raha hai. Kahin pahunch hi nahi raha.'),
  (110, 'Darwaza band hone se ek second pehle ghus gaya.'),
  (111, 'Machine khol kar har chhota part dekh liya.'),
  (112, 'Saaf aasman se achanak kuch gir pada.'),
  (113, 'Dusre ka show chheen kar khud hero ban gaya.'),
  (114, 'Rassi khinchne me poori taqat laga di.'),
  (115, 'Peechhe mud kar seedha bhaag nikla.'),
  (116, 'Dil shirt ki sleeve par latka hua hai. Sab dekh sakte hain.'),
  (117, 'Helicopter se poora shehar ek saath dikh raha hai.'),
  (118, 'Zakhm par namak bhi chhidak diya.'),
  (119, 'Game haar gaye. Dobara Start wale square par aa gaye.'),
  (120, 'Chhoti machhli chhod, badi machhli pakadne chala gaya.'),
  (121, 'Kabhi garam, kabhi thanda. Faisla hi nahi kar raha.'),
  (122, 'Hawa me mahal bana raha hai.'),
  (123, 'Samundar me ek boond paani gira di.'),
  (124, 'Ghoda poori balti bhar kar kha raha hai.'),
  (125, 'Seedha match jeeta. Koi cheating nahi.'),
  (126, 'Beans kha kar energy se uchhal raha hai.'),
  (127, 'Kaale aur safed kagaz par sab likha hua hai.'),
  (128, 'Khushi se chehra chamak raha hai.'),
  (129, 'Ek patthar se do panchhi gir gaye.'),
  (130, 'Kitabon ke dher ke beech baitha likh raha hai.'),
  (131, 'Sukhe tinke ka aadmi. Bilkul kamzor.'),
  (132, 'Bina music sheet ke kaan se dhun baja raha hai.'),
  (133, 'Ghar ka har kona chamak raha hai.'),
  (134, 'Bhed ki khaal me bhediya chhupa hai.'),
  (135, 'Sir par madhumakkhi baithi hai. Bas usi baat ka junoon.'),
  (136, 'Kadvi goli nigalni hi padi.'),
  (137, 'Blade chehre ko bas halka sa chhoo kar nikal gaya.'),
  (138, 'Patakha ek baar chamka aur turant bujh gaya.'),
  (139, 'Sab kuch khule aam. Kuch chhupa nahi.'),
  (140, 'Ghadi se race laga kar kaam kar raha hai.'),
  (141, 'Kheera bilkul thanda. Koi tension nahi.'),
  (142, '6 aur 7 ulte-pulte pade hain. Sab gadbad hai.'),
  (143, 'Billi ke gale me ghanti baandhne sab darte hain.'),
  (144, 'Ek taraf pahad, doosri taraf gehri khai.'),
  (145, 'Dhool me gir gaya. Haar gaya.'),
  (146, 'Magarmachh ro raha hai, par aansu nakli hain.'),
  (147, 'Test me standard paar kar liya.'),
  (148, 'Seedha climax par aa gaya. Faltu baat chhod di.'),
  (149, 'Dusre ko wahi dawa pila di jo khud pilata tha.'),
  (150, 'Bikhri hui team line me aa gayi. Ab sab ready.'),
  (151, 'Baraf ka pahad. Upar chhota, neeche bahut bada.'),
  (152, 'Pura bag ulat diya. Billi bahar aa gayi.'),
  (153, 'Teer nikal chuka hai. Ab wapas nahi aayega.'),
  (154, 'Do kursiyon ke beech khada hai. Kahan baithe samajh nahi aa raha.'),
  (155, 'Khali barrel sabse zyada awaaz kar raha hai.'),
  (156, 'Kaan me dheere se raaz bol diya.'),
  (157, 'Chingari ko hawa mili aur aag ban gayi.'),
  (158, 'Andhere me teer chala raha hai.'),
  (159, 'Darwaze ki chabi usi ke haath me hai.'),
  (160, 'Aankh me dhool jhonk kar nikal gaya.'),
  (161, 'Naak bahut upar. Kisi ko ghaas nahi daal raha.'),
  (162, 'Patte khol diye. Ab sabko sach pata hai.'),
  (163, 'Chuhe ki tarah chupchaap nikal gaya.'),
  (164, 'Sikke ke dono side dekh raha hai.'),
  (165, 'Kaan se dhuaan nikal raha hai. Bahut gussa hai.'),
  (166, 'Bahte paani ke saath hi beh gaya.'),
  (167, 'Ek hi jhatke me saaf mana kar diya.'),
  (168, 'Deewar par likha sabko dikh raha hai.'),
  (169, 'Do pakshiyon ke beech shanti ka safed jhanda.'),
  (170, 'Rassi par chal raha hai. Zara si galti aur gir jayega.'),
  (171, 'Haath jod kar madad maang raha hai.'),
  (172, 'Darwaza khula tha. Bas mauka pakad liya.'),
  (173, 'Nadi ka paani pul ke neeche se bahut aage nikal gaya.'),
  (174, 'Do log ek hi page padh rahe hain.'),
  (175, 'Hawa ka rukh dekhkar jhanda ghoom gaya.'),
  (176, 'Chhota beej bada ped ban gaya.'),
  (177, 'Kandhon se bahut bada bojh utar gaya.'),
  (178, 'Aankhon ke saamne parda hata. Sab saaf dikhne laga.'),
  (179, 'Dil ke andar ki baat muh se nikal gayi.'),
  (180, 'Ek haath se taali bajane ki koshish kar raha hai.'),
  (181, 'Baraf pighal gayi. Sab normal ho gaya.'),
  (182, 'Ghoda astabal se nikal chuka. Gate baad me band kiya.'),
  (183, 'Aankh band karke seedha chhalang laga di.'),
  (184, 'Ek hi tokri me saare ande rakh diye.'),
  (185, 'Andhera hi andhera. Door ek chhoti si roshni dikh rahi hai.'),
  (186, 'Hawa ke khilaaf cycle chala raha hai.'),
  (187, 'Chhota patthar pahad se ludhak kar bada pahad ban gaya.'),
  (188, 'Jeb me haath dala. Kuch bhi nahi nikla.'),
  (189, 'Aag aur paani ko ek saath milane ki koshish.'),
  (190, 'Muh par tala laga liya.'),
  (191, 'Deewar ke bhi kaan hain. Dheere bolo.'),
  (192, 'Teer bilkul nishane par laga.'),
  (193, 'Sab patte haath me hote hue bhi chup baitha hai.'),
  (194, 'Chhoti chingari se poora jungle jal gaya.'),
  (195, 'Haath se ret ki tarah mauka fisal gaya.'),
  (196, 'Seedhi par pehla kadam rakh diya.'),
  (197, 'Hawa ka rukh achanak badal gaya.'),
  (198, 'Bahut der baad bulb jal gaya. Idea aa gaya.'),
  (199, 'Aakhri eent lagte hi poori deewar tayyar ho gayi.'),
  (200, 'Finish line paar karke dono haath upar kar diye. Kaam complete.')
)
UPDATE public.ssc_black_book_items t
SET hint = h.hint
FROM ordered o
JOIN hints h ON h.rn = o.rn
WHERE t.id = o.id;